const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let type='Aadhaar Card',file=null,records=JSON.parse(localStorage.getItem('idshield')||'[]'),logs=JSON.parse(localStorage.getItem('idlogs')||'[]');
function toast(x){let t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}function log(x){logs.unshift(new Date().toLocaleString()+' — '+x);localStorage.setItem('idlogs',JSON.stringify(logs));renderLogs()}
function nav(p){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+p).classList.add('active');$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#sidebar').classList.remove('open');if(p==='dashboard')renderDash();if(p==='verifications')renderHistory();}
document.addEventListener('click',e=>{let b=e.target.closest('[data-page]');if(b)nav(b.dataset.page)});$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#logout').onclick=()=>{log('Logout');toast('Signed out of demo session')};$('#bell').onclick=()=>toast('6 notifications');
const types=['Aadhaar Card','PAN Card','Passport','Driving Licence','Voter ID','Government ID','Other Document'];function makeTypes(id){$(id).innerHTML=types.map(x=>`<button class="type ${x===type?'selected':''}" data-type="${x}">▣<small>${x}</small></button>`).join('');$(id).onclick=e=>{let b=e.target.closest('[data-type]');if(b){type=b.dataset.type;makeTypes('#types');makeTypes('#mainTypes')}}}makeTypes('#types');makeTypes('#mainTypes');
function valid(f){if(!f)return'Choose a file.';if(f.size>10*1024*1024)return'Maximum file size is 10MB.';if(!['image/jpeg','image/png','application/pdf'].includes(f.type)&&! /\.(jpg|jpeg|png|pdf)$/i.test(f.name))return'Only JPG, PNG and PDF are supported.';return''}
function setFile(f){let e=valid(f);if(e){toast(e);return}file=f;let html=`<div class="fileinfo">✓ ${f.name} · ${(f.size/1048576).toFixed(2)} MB</div>`;$('#info').innerHTML=html;$('#mainInfo').innerHTML=html;$('#continue').disabled=false;let p=$('#preview');if(f.type==='application/pdf')p.innerHTML=`<iframe src="${URL.createObjectURL(f)}"></iframe>`;else p.innerHTML=`<img src="${URL.createObjectURL(f)}" alt="Uploaded document">`;log('Uploaded '+f.name)}
$('#browse').onclick=()=>$('#file').click();$('#mainBrowse').onclick=()=>$('#mainFile').click();$('#file').onchange=e=>setFile(e.target.files[0]);$('#mainFile').onchange=e=>setFile(e.target.files[0]);$('#replace').onclick=()=>$('#mainFile').click();$('#remove').onclick=()=>{file=null;$('#preview').textContent='No document selected';$('#continue').disabled=true;$('#info').innerHTML='';$('#mainInfo').innerHTML=''};
function drop(id){let d=$(id);['dragenter','dragover'].forEach(x=>d.addEventListener(x,e=>{e.preventDefault();d.style.background='#eef2ff'}));d.addEventListener('dragleave',()=>d.style.background='');d.addEventListener('drop',e=>{e.preventDefault();d.style.background='';setFile(e.dataTransfer.files[0])})}drop('#drop');
$('#continue').onclick=()=>{if(!file)return;$('#modal').classList.remove('hidden');let a=['Pre-processing','OCR & extraction','Document structure analysis','Tampering detection','Information consistency','Risk scoring'];let i=0;let tm=setInterval(()=>{$('#progressText').textContent=a[i++];if(i===a.length){clearInterval(tm);setTimeout(result,400)}},500)};
function result(){let suspicious=/fake|tamper|edited/i.test(file.name),risk=suspicious?82:18,name='Rahul Kumar',id='VER-'+Date.now().toString().slice(-8),level=risk<=30?'Low Risk':risk<=60?'Medium Risk':'High Risk';let r={id,type,name,risk,level,date:new Date().toLocaleString(),file:file.name,findings:suspicious?['Possible text-region alteration detected','Document structure anomaly','Information consistency warning']:['No significant manipulation indicators detected','OCR confidence high','Information fields internally consistent']};records.unshift(r);localStorage.setItem('idshield',JSON.stringify(records));$('#modal').classList.add('hidden');renderReport(r);renderDash();log('Completed analysis '+id);nav('reports');toast('Analysis completed — '+level)}
function renderDash(){let l=records.filter(r=>r.risk<=30).length,m=records.filter(r=>r.risk>30&&r.risk<=60).length,h=records.filter(r=>r.risk>60).length;$('#total').textContent=records.length;$('#low').textContent=l;$('#med').textContent=m;$('#high').textContent=h;$('#recent').innerHTML=records.slice(0,6).map(r=>`<tr><td>${r.id}</td><td>${r.type}</td><td>${r.name}</td><td>${r.risk}/100</td><td>${r.level}</td><td>${r.date}</td></tr>`).join('')||'<tr><td colspan="6">No verifications yet.</td></tr>'}
function renderHistory(){let q=($('#search')?.value||'').toLowerCase(),f=$('#filter')?.value||'';let a=records.filter(r=>(!q||`${r.id} ${r.name} ${r.type}`.toLowerCase().includes(q))&&(!f||r.level===f));$('#history').innerHTML=a.map(r=>`<tr><td>${r.id}</td><td>${r.type}</td><td>${r.name}</td><td>${r.risk}/100</td><td>${r.level}</td><td>${r.date}</td></tr>`).join('')||'<tr><td colspan="6">No matching records.</td></tr>'}$('#search').oninput=renderHistory;$('#filter').onchange=renderHistory;
function renderReport(r){$('#report').innerHTML=`<div class="head"><h2>Verification Report · ${r.id}</h2><b>${r.risk}/100 — ${r.level}</b></div><hr><p><b>Document:</b> ${r.type}</p><p><b>Extracted Name:</b> ${r.name}</p><p><b>Uploaded File:</b> ${r.file}</p><p><b>Date:</b> ${r.date}</p><h3>Analysis Findings</h3><ul>${r.findings.map(x=>`<li>${x}</li>`).join('')}</ul><p><b>Recommendation:</b> ${r.risk>60?'Manual Verification Required':'Proceed to authorized verification'}</p><small>This is AI-assisted preliminary screening. Final verification remains with an authorized human officer.</small>`}$('#print').onclick=()=>window.print();function renderLogs(){$('#audits').innerHTML=logs.map(x=>`<p>${x}</p>`).join('')||'<div class="empty">No audit activity.</div>'}renderDash();renderHistory();renderLogs();
